config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookmarks
  root 'bookmarks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :url, presence: true
  before_save :fetch_title
  belongs_to :user

  def fetch_title
    begin
      uri = URI.parse(url)
      response = Net::HTTP.get(uri).force_encoding(Encoding::UTF_8)
      captures = /<title>(?<title>.+)<\/title>/m.match(response).named_captures
      self.title = captures['title']
    rescue => e
      logger.warn "Fetch Title Failed.url = [#{url}],error = #{e.message}"
    end
    false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])

  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :bookmark_search, only: [:index, :show, :new, :edit]
  # GET /bookmarks
  # GET /bookmarks.json
  def index

    @bookmarks = @q.result(distinct: true).page(params[:page]).order('created_at desc').per(10)

  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    if @bookmark.user_id != current_user.id
      redirect_to root_path
    end
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
    if @bookmark.user_id != current_user.id
      redirect_to root_path
    end
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to root_path, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to root_path, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    if @bookmark.user_id != current_user.id
      redirect bookmark_path
    else
      @bookmark.destroy
      respond_to do |format|
        format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bookmark_params
    params.require(:bookmark).permit(:url, :title, :description).merge(user_id: current_user.id)
  end

  def bookmark_search

    @q = current_user.bookmarks.ransack(params[:q])
    @url = request.url

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.haml
= form_with(model: bookmark, local: true) do |form|
  - if bookmark.errors.any?
    #error_explanation
      %p
        = pluralize(bookmark.errors.count, "error")
        prohibited this bookmark from being saved:
      %ul
        - bookmark.errors.full_messages.each do |message|
          %li
            =message
  .field
    = form.label :url
    = form.text_field :url, class: "form-control form-control-sm", placeholder: "example.com"
    = form.label :description
    = form.text_area :description, row: 5, class: "form-control form-control-sm"
  .actions
    = form.submit class: 'btn btn-primary p-1 mt-2'

app/views/bookmarks/_navbar.html.haml
.nav-wrapper
  %p#notice= notice
  %nav.navbar.navbar-light.mb-1.mr-2
    = link_to '64page',root_path, class: 'page36 text-dark'



    -if current_user
      .user-info
        %p.mx-1
          = link_to current_user.name, edit_user_registration_path, class: 'border_spread_btn mx-2'
          |
          = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'border_spread_btn ml-2', data: { confirm: "ログアウトします。よろしいですか？"}
    - else
      .user-info
      %p.mx-1
        = link_to 'Log in', new_user_session_path, class: 'border_spread_btn mx-2'
        |
        = link_to 'Sign up', new_registration_path(resource_name), class: 'border_spread_btn ml-2'

app/views/bookmarks/edit.html.haml
.wrapper
  = render 'navbar'
  .show-wrapper
    %h4.font-weight-bold.mb-2 Editing Bookmark
    -#%p Title:
    = @bookmark.title
    = render 'form', bookmark: @bookmark
    = link_to 'Delete', @bookmark, method: :delete,class: 'border_spread_btn mr-2', data: {confirm: "#{@bookmark.title ||= @bookmark.url} を削除します。よろしいですか？"}
    |
    = link_to 'Top page', root_path, class: 'border_spread_btn ml-2 mt-5'

app/views/bookmarks/index.html.haml
.wrapper
  = render 'navbar'
  .content-wrapper
    = link_to 'New Bookmark', new_bookmark_path, class: 'border_spread_btn mb-3'
    %h6.mt-5 Search by title or URL
    = search_form_for @q do |f|
      .search-box.row.align-items-center
        .col-auto
          = f.search_field :title_cont, class: 'form-control form-control-sm', placeholder: 'Enter title to search'
        .col-auto
          = f.search_field :url_cont, class: 'form-control form-control-sm', placeholder: 'Enter URL to search'
        .col-auto
          = f.submit class: 'btn btn-primary p-1'
    %table.table.table-hover.mt-3
      %thead
        %tr
          %th Title
          %th{colspan: "3"}
      %tbody
        - @bookmarks.each do |bookmark|
          %tr
            %td= link_to bookmark.title, bookmark.url, target: "_blank", class: 'bookmark-title'
            %td= link_to 'Edit', edit_bookmark_path(bookmark), class: 'border_spread_btn'

    .mb-3.mt-5
      = paginate @bookmarks
      = page_entries_info @bookmarks

app/views/bookmarks/new.html.haml
.wrapper
  = render 'navbar'
  .login-wrapper
    %h4 New Bookmark
    = render 'form', bookmark: @bookmark
    = link_to 'Back', bookmarks_path, class: 'border_spread_btn'

app/views/bookmarks/show.html.haml
.wrapper
  = render 'navbar'
  .show-wrapper
    %p
      %strong Title:
      =  simple_format @bookmark.title
    %p
      %strong Url:
      = simple_format @bookmark.url
      -#= link_to @bookmark.url, @bookmark.url, target: "_blank"
    %p
      %strong Description
    %div.mb-5.mt-5
      = @bookmark.description
    = link_to 'Edit', edit_bookmark_path(@bookmark),class: 'border_spread_btn mr-2'
    |
    = link_to 'Delete', @bookmark, method: :delete,class: 'border_spread_btn mx-2', data: {confirm: "#{@bookmark.title ||= @bookmark.url} を削除します。よろしいですか？"}
    |
    = link_to 'Top page', root_path, class: 'border_spread_btn ml-2'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bookmarks
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield